project:
  type: website
  # output-dir: docs


website:
  title: "ASG Website" # Title
  description: "ASG Website" # Description of the place
  site-url: https://alejandrosgz.github.io/ASG_Website # URL web
  repo-url: https://alejandrosgz.github.io/ASG_Website/
  open-graph: true
  #google-analytics: # Control visitas
  #   tracking-id: "UA-XXXXXXXX"
  #   anonymize-ip: true
  # cookie-consent: true


  navbar: # Structure --> Navigation bar
    right: # Position
      - href: index.qmd # Main
        text: Home
      - text: Research # Parent menu without href
        menu: # Dropdown menu
          - text: "Publications"
            href: Publications.qmd
          - text: "Projects"
            href: Projects.qmd
      - href: Blog.qmd
        text: "Blog"

  page-footer:
    background: light
    right: "Made with Quarto"
   # back-to-top-navigation: true


format:
  html:
    theme: flatly
    #css: styles.css
    toc: false

execute:
  freeze: auto  # re-render only when source changes. Only run what it has been changed



