---
title: "Publications"
listing:
  contents: publications # Folder with further files/pages
  type: grid # To make it as a grid
  categories: false
---

**Journal Articles**

E. Molina-Navarro, A. Sánchez-Gómez & S. Martínez-Pérez. (2024). Innovating on Hydrological Modelling Calibration Towards a Realistic Simulation of Climate Change Impacts on Water Resources. *Earth Systems and Environment*. 1-18. [https://doi.org/10.1007/s41748-024-00462-5](https://doi.org/10.1007/s41748-024-00462-5)


A. Sánchez-Gómez, C. Schürz, E. Molina-Navarro & K. Bieger. (2024). Groundwater modelling in SWAT+: Considerations for a realistic baseflow simulation. *Groundwater for Sustainable Development*. 26, 101275. [https://doi.org/10.1016/j.gsd.2024.101275](https://doi.org/10.1016/j.gsd.2024.101275)


A. Sánchez-Gómez, K. Bieger, C. Schürz, S. Martínez-Pérez, H. Rathjens & E. Molina-Navarro. (2024). HydRoVars: an R tool to collect hydrological variables. *Journal of Hydroinformatics*. 26 (5), 1150-1166. [https://doi.org/10.2166/hydro.2024.293](https://doi.org/10.2166/hydro.2024.293)


A. Sánchez-Gómez, S. Martinez-Perez, S. Leduc, A. Sastre-Merlin, E. Molina-Navarro (2023). Streamflow components and climate change: Lessons learnt and energy implications after hydrological modeling experiences in catchments with a Mediterranean climate. *Energy Reports*. 9, 277-291. [https://doi.org/10.1016/j.egyr.2022.11.191](https://doi.org/10.1016/j.egyr.2022.11.191)


J. Martínez-Fernández, E. Molina-Navarro, Á. González-Zamora, A. Sánchez-Gómez, L. Almendra-Martín. (2023). SWAT soil moisture assessment under Mediterranean conditions: An intercomparison analysis in the Henares basin (Spain). *Journal of Hydrology: Regional Studies*. 48, 101460. [https://doi.org/10.1016/j.ejrh.2023.101460](https://doi.org/10.1016/j.ejrh.2023.101460)


A. Sánchez-Gómez, S. Martínez-Pérez, F.M. Pérez-Chavero & E. Molina-Navarro. (2022). Optimization of a SWAT model by incorporating geological information through calibration strategies. *Optimization and Engineering*. 23 (4), 2203-2233. [https://doi.org/10.1007/s11081-022-09744-1](https://doi.org/10.1007/s11081-022-09744-1)


Y. Asensio, M. Llorente, A. Sánchez-Gómez, C. Manchon, K. Boltes & A. Esteve-Núñez (2021). Microbial electrochemical fluidized bed reactor: a promising solution for removing pollutants from pharmaceutical industrial wastewater. *Frontiers in Microbiology*. 12, 737112. [https://doi.org/10.3389/fmicb.2021.737112](https://doi.org/10.3389/fmicb.2021.737112)


